export {
  ANCHORING_REQUIREMENTS,
  ANCHORING_FILTER_VALUES,
  ASSEMBLY_REQUIREMENTS,
  FLOORING_REQUIREMENTS,
  PRODUCT_ID_PATTERN,
  PRODUCT_CATEGORIES,
  TRAINING_GOALS,
  productMountingSchema,
  productSchema,
  type EffectiveMounting,
  type Product,
  type ProductMounting,
  type AnchoringFilter,
  type ProductCategory,
  type TrainingGoal,
} from "./product";
