import type { ProjectStore } from "@/features/creator/store/project-store";

import { searchProductsWebMcpTool } from "./register-catalog-tools";
import {
  createPlaceProductHandler,
  createRemoveProductHandler,
  createUpdatePlacementHandler,
} from "./placement-tool-handlers";
import {
  createAddObstacleHandler,
  createAddWallElementHandler,
  createConfigureRoomHandler,
  createGetProjectStateHandler,
  createRemoveObstacleHandler,
  createRemoveWallElementHandler,
  createUpdateObstacleHandler,
  createUpdateWallElementHandler,
  createUpdateProjectSettingsHandler,
  createValidateLayoutHandler,
} from "./room-tool-handlers";
import {
  addObstacleJsonSchema,
  addWallElementJsonSchema,
  configureRoomJsonSchema,
  getProjectStateJsonSchema,
  removeObstacleJsonSchema,
  removeWallElementJsonSchema,
  placeProductJsonSchema,
  removeProductJsonSchema,
  updatePlacementJsonSchema,
  updateObstacleJsonSchema,
  updateWallElementJsonSchema,
  updateProjectSettingsJsonSchema,
  validateLayoutJsonSchema,
} from "./room-tool-schemas";
import { registerToolSet, type ToolSetRegistrationResult } from "./register-tool-set";
import type { WebMcpTool } from "./types";

const SPATIAL_INPUT_NOTE =
  "Positions are the minimum corner of the rotated footprint. Dimensions and positions use integer centimeters; rotation is 0, 90, 180, or 270 degrees. Spatially invalid layouts may still be applied and returned with validation issues.";

export function createRoomWebMcpTools(store: ProjectStore): readonly WebMcpTool[] {
  return [
    {
      name: "get_project_state",
      title: "Get current room project state",
      description:
        "Read the live version-3 room project, settings, floor obstacles, wall elements, catalog equipment placements, deterministic validation, revision, and manual undo/redo availability. Canonical room IDs from this result can be used by the currently registered update and remove tools.",
      inputSchema: getProjectStateJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createGetProjectStateHandler(store),
    },
    {
      name: "configure_room",
      title: "Configure room dimensions",
      description: `Set the room width, depth, and height in positive integer centimeters. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: configureRoomJsonSchema,
      execute: createConfigureRoomHandler(store),
    },
    {
      name: "update_project_settings",
      title: "Update room project settings",
      description:
        "Update a non-empty patch containing the non-negative integer PLN budget and/or up to five canonical training goals. This creates one shared manual undo step when values change.",
      inputSchema: updateProjectSettingsJsonSchema,
      execute: createUpdateProjectSettingsHandler(store),
    },
    {
      name: "add_obstacle",
      title: "Add a room obstacle or unavailable zone",
      description: `Add a physical obstacle or unavailable zone. The canonical obstacle ID is generated by the project and returned; callers must not supply an ID. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: addObstacleJsonSchema,
      execute: createAddObstacleHandler(store),
    },
    {
      name: "update_obstacle",
      title: "Update a room obstacle or unavailable zone",
      description: `Update one canonical obstacle ID using a non-empty patch. A locked obstacle accepts only the exact patch { locked: false } until unlocked. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: updateObstacleJsonSchema,
      execute: createUpdateObstacleHandler(store),
    },
    {
      name: "remove_obstacle",
      title: "Remove a room obstacle or unavailable zone",
      description:
        "Remove the obstacle or unavailable zone with a canonical ID returned by get_project_state or add_obstacle. Locked obstacles must be unlocked first.",
      inputSchema: removeObstacleJsonSchema,
      execute: createRemoveObstacleHandler(store),
    },
    {
      name: "add_wall_element",
      title: "Add a door or window",
      description:
        "Add a minimal door or window to a wall using its offset and width in integer centimeters. The project generates and returns its canonical ID. No unavailable zone is created or implied.",
      inputSchema: addWallElementJsonSchema,
      execute: createAddWallElementHandler(store),
    },
    {
      name: "update_wall_element",
      title: "Update a door or window",
      description:
        "Update one door or window by canonical wall-element ID using a non-empty patch of name, wall, offset, or width. Its kind is immutable. This never creates or changes an unavailable zone.",
      inputSchema: updateWallElementJsonSchema,
      execute: createUpdateWallElementHandler(store),
    },
    {
      name: "remove_wall_element",
      title: "Remove a door or window",
      description:
        "Remove a door or window using a canonical wall-element ID returned by get_project_state or add_wall_element. Removing it does not remove or otherwise change any unavailable zone.",
      inputSchema: removeWallElementJsonSchema,
      execute: createRemoveWallElementHandler(store),
    },
    {
      name: "validate_layout",
      title: "Validate the current room layout",
      description:
        "Read the live deterministic layout validation and its revision without changing state or history. Reports physical and clearance bounds, collisions, unavailable-zone conflicts, equipment ceiling and budget requirements, wall bounds, and same-wall overlap issues for canonical entity IDs.",
      inputSchema: validateLayoutJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createValidateLayoutHandler(store),
    },
    searchProductsWebMcpTool,
    {
      name: "place_product",
      title: "Place catalog equipment in the room",
      description: `Place one canonical catalog product in the live room. The project generates and returns a placement ID; callers must not supply one. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: placeProductJsonSchema,
      execute: createPlaceProductHandler(store),
    },
    {
      name: "update_placement",
      title: "Move or rotate placed equipment",
      description: `Update one canonical placement ID using a non-empty position and/or rotation patch. The product identity is immutable. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: updatePlacementJsonSchema,
      execute: createUpdatePlacementHandler(store),
    },
    {
      name: "remove_product",
      title: "Remove placed equipment from the room",
      description:
        "Remove one equipment instance using its canonical placement ID returned by get_project_state or place_product. This does not remove or modify the catalog product.",
      inputSchema: removeProductJsonSchema,
      execute: createRemoveProductHandler(store),
    },
  ];
}

export function registerRoomTools(
  documentValue: Document,
  controller: AbortController,
  store: ProjectStore,
): Promise<ToolSetRegistrationResult> {
  return registerToolSet(documentValue, controller, createRoomWebMcpTools(store));
}
