import type { ProjectStore } from "@/features/creator/store/project-store";
import {
  createApplyLayoutChangesHandler,
  createEvaluateLayoutChangesHandler,
  createSuggestPlacementsHandler,
} from "./batch-tool-handlers";
import { layoutChangesJsonSchema, suggestPlacementsJsonSchema } from "./batch-tool-schemas";

import { searchProductsWebMcpTool } from "./register-catalog-tools";
import {
  createAddProductToProjectHandler,
  createPlaceProductHandler,
  createPlaceProjectItemHandler,
  createRemoveProductHandler,
  createUnplaceProductHandler,
  createUpdatePlacementHandler,
} from "./placement-tool-handlers";
import {
  createAddObstacleHandler,
  createAddWallElementHandler,
  createConfigureRoomHandler,
  createGetProjectStateHandler,
  createRemoveObstacleHandler,
  createRemoveWallElementHandler,
  createUpdateObstacleHandler,
  createUpdateWallElementHandler,
  createUpdateProjectSettingsHandler,
  createValidateLayoutHandler,
} from "./room-tool-handlers";
import {
  addObstacleJsonSchema,
  addProductToProjectJsonSchema,
  addWallElementJsonSchema,
  configureRoomJsonSchema,
  getProjectStateJsonSchema,
  placeProjectItemJsonSchema,
  removeObstacleJsonSchema,
  removeWallElementJsonSchema,
  placeProductJsonSchema,
  removeProductJsonSchema,
  unplaceProductJsonSchema,
  updatePlacementJsonSchema,
  updateObstacleJsonSchema,
  updateWallElementJsonSchema,
  updateProjectSettingsJsonSchema,
  validateLayoutJsonSchema,
} from "./room-tool-schemas";
import { registerToolSet, type ToolSetRegistrationResult } from "./register-tool-set";
import type { WebMcpTool } from "./types";

const SPATIAL_INPUT_NOTE =
  "Positions are the minimum corner of the rotated footprint. Dimensions and positions use integer centimeters; rotation is 0, 90, 180, or 270 degrees. Spatially invalid layouts may still be applied and returned with validation issues.";
const ACCESS_NOTE =
  "Results carry reachability facts. A walking path must stay at least 75 cm wide, and a path narrower than 100 cm is reported as tight; both widths are application conventions, not building codes. Unreachable doors and equipment are errors, not trade-offs. ACCESS_NOT_EVALUATED means the room has no door, so access was not judged. Inspect validation.access, validation.valid, and accessImpact on mutations.";
const POST_MUTATION_VALIDATION_NOTE =
  `The call succeeds even when the resulting layout is invalid; read validation.valid, validation.errorCount, and validation.warningCount and report them to the user. ${ACCESS_NOTE}`;

export function createRoomWebMcpTools(store: ProjectStore): readonly WebMcpTool[] {
  return [
    {
      name: "get_project_state",
      title: "Get current room project state",
      description:
        "Read the live version-4 room project, settings, floor obstacles, wall elements, project items, catalog equipment placements, deterministic validation, revision, and manual undo/redo availability. Canonical room IDs from this result can be used by the currently registered update and remove tools. Selection-only products appear as items without placements. " + ACCESS_NOTE,
      inputSchema: getProjectStateJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createGetProjectStateHandler(store),
    },
    {
      name: "configure_room",
      title: "Configure room dimensions",
      description: `Set the room width, depth, and height in positive integer centimeters. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: configureRoomJsonSchema,
      execute: createConfigureRoomHandler(store),
    },
    {
      name: "update_project_settings",
      title: "Update room project settings",
      description:
        "Update a non-empty patch containing the non-negative integer PLN budget and/or up to five canonical training goals. This creates one shared manual undo step when values change.",
      inputSchema: updateProjectSettingsJsonSchema,
      execute: createUpdateProjectSettingsHandler(store),
    },
    {
      name: "add_obstacle",
      title: "Add a room obstacle or unavailable zone",
      description: `Add a physical obstacle or unavailable zone. The canonical obstacle ID is generated by the project and returned; callers must not supply an ID. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: addObstacleJsonSchema,
      execute: createAddObstacleHandler(store),
    },
    {
      name: "update_obstacle",
      title: "Update a room obstacle or unavailable zone",
      description: `Update one canonical obstacle ID using a non-empty patch. A locked obstacle accepts only the exact patch { locked: false } until unlocked. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: updateObstacleJsonSchema,
      execute: createUpdateObstacleHandler(store),
    },
    {
      name: "remove_obstacle",
      title: "Remove a room obstacle or unavailable zone",
      description:
        "Remove the obstacle or unavailable zone with a canonical ID returned by get_project_state or add_obstacle. Locked obstacles must be unlocked first.",
      inputSchema: removeObstacleJsonSchema,
      execute: createRemoveObstacleHandler(store),
    },
    {
      name: "add_wall_element",
      title: "Add a door or window",
      description:
        "Add a minimal door or window to a wall using its offset and width in integer centimeters. The project generates and returns its canonical ID. No unavailable zone is created or implied.",
      inputSchema: addWallElementJsonSchema,
      execute: createAddWallElementHandler(store),
    },
    {
      name: "update_wall_element",
      title: "Update a door or window",
      description:
        "Update one door or window by canonical wall-element ID using a non-empty patch of name, wall, offset, or width. Its kind is immutable. This never creates or changes an unavailable zone.",
      inputSchema: updateWallElementJsonSchema,
      execute: createUpdateWallElementHandler(store),
    },
    {
      name: "remove_wall_element",
      title: "Remove a door or window",
      description:
        "Remove a door or window using a canonical wall-element ID returned by get_project_state or add_wall_element. Removing it does not remove or otherwise change any unavailable zone.",
      inputSchema: removeWallElementJsonSchema,
      execute: createRemoveWallElementHandler(store),
    },
    {
      name: "validate_layout",
      title: "Validate the current room layout",
      description:
        "Read the live deterministic layout validation and its revision without changing state or history. Reports errors and warnings separately: valid is true when errorCount is 0 even if warningCount is greater than 0. Physical collisions, room and wall bounds, unavailable-zone conflicts, use zones leaving the room or hitting obstacles, ceiling height, budget, blocked doors, disconnected doors, and unreachable equipment remain errors. Equipment occupying another item's use zone, or two overlapping use zones, are warnings. An unapproachable physical obstacle is a warning. Access facts distinguish reachable, tight, and unreachable: a walking path must stay at least 75 cm wide, and a path narrower than 100 cm is reported as tight (application conventions, not building codes). Geometry no taller than 20 cm, such as a bare barbell or a walking pad, is stepped over rather than walked around, so it never divides the room; it still occupies floor area for collision, bounds, and reach checks. Unreachable entities are errors, not trade-offs. A project with no door reports ACCESS_NOT_EVALUATED and does not judge targets; that is missing input, not an accepted layout. Inspect validation.valid, validation.errorCount, validation.warningCount, and validation.access.",
      inputSchema: validateLayoutJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createValidateLayoutHandler(store),
    },
    searchProductsWebMcpTool,
    {
      name: "place_product",
      title: "Place catalog equipment in the room",
      description: `Create one project item and place it on the floor in a single undo step. Use add_product_to_project for selection-only accessories or to add a floor product without placing it. The project generates and returns placement and item IDs; callers must not supply them. Wall-mounted products must sit flush against the wall implied by rotation: 0 top, 90 right, 180 bottom, 270 left. They must not cross a door or window on that wall. The call does not snap or correct an off-wall position; read WALL_MOUNT_OFF_WALL and WALL_MOUNT_OVERLAPS_OPENING on the returned validation. Selection-only products are rejected without mutation. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: placeProductJsonSchema,
      execute: createPlaceProductHandler(store),
    },
    {
      name: "add_product_to_project",
      title: "Add a catalog product to the project without placing it",
      description:
        "Add one canonical catalog product as an unplaced project item. It counts toward budget and training-goal coverage immediately. Use place_project_item later for floor-capable products. Selection-only products cannot be placed. The project generates and returns a project item ID.",
      inputSchema: addProductToProjectJsonSchema,
      execute: createAddProductToProjectHandler(store),
    },
    {
      name: "place_project_item",
      title: "Place an existing project item on the floor",
      description: `Place one unplaced floor-capable project item. Selection-only items and already placed items are rejected without mutation. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: placeProjectItemJsonSchema,
      execute: createPlaceProjectItemHandler(store),
    },
    {
      name: "update_placement",
      title: "Move or rotate placed equipment",
      description: `Update one canonical placement ID using a non-empty position and/or rotation patch. The product identity is immutable. ${SPATIAL_INPUT_NOTE} ${POST_MUTATION_VALIDATION_NOTE}`,
      inputSchema: updatePlacementJsonSchema,
      execute: createUpdatePlacementHandler(store),
    },
    {
      name: "unplace_product",
      title: "Remove equipment from the floor without deleting it",
      description:
        "Remove one floor placement by canonical placement ID. The project item stays in the project, shopping list, and budget. Use remove_product to delete the item itself.",
      inputSchema: unplaceProductJsonSchema,
      execute: createUnplaceProductHandler(store),
    },
    {
      name: "remove_product",
      title: "Remove a project item and any floor placement",
      description:
        "Remove one project item using its canonical projectItemId returned by get_project_state, add_product_to_project, or place_product. If the item is placed, that placement is removed in the same command. The result enumerates the cascade. This does not remove or modify the catalog product.",
      inputSchema: removeProductJsonSchema,
      execute: createRemoveProductHandler(store),
    },
    {
      name: "suggest_placements",
      title: "Suggest safe equipment placements",
      description:
        "Read deterministic placement suggestions without changing the project or history. Supply exactly one productId or projectItemId; an already placed item is repositioned in memory, and its current pose may be returned if it is already a best fit (applying that pose is a no-op). Scan minimum-corner positions on a 10 cm grid in z, x, then 0/90/180/270 order, filtered by optional rotations and inclusive region bounds. Return the best 3 candidates by default (maximum 10), exact commands, warning penalties, and rejection counts. Errors and any unreachable entity reject a candidate; warnings increase its score. No door means access was not evaluated. Searches above 20,000 candidates are rejected; with doors, at most 20,000 room grid cells and 30 million candidate-cell evaluations are allowed. Narrow region or rotations for large searches. Apply a chosen command explicitly with apply_layout_changes; suggestions are never accepted automatically.",
      inputSchema: suggestPlacementsJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createSuggestPlacementsHandler(store),
    },
    {
      name: "evaluate_layout_changes",
      title: "Evaluate hypothetical layout changes",
      description:
        "Evaluate an ordered changes array of 1–25 existing project commands in memory. Never mutates the project, revision, or undo history. Returns applies, full hypothetical validation and error/warning count deltas; command failures identify their zero-based index. Errors and any unreachable entity make applies false, while warnings are allowed. Generated preview IDs are temporary, not IDs to reference in later commands. Use the same payload with apply_layout_changes after inspection; the live state is checked again at apply time.",
      inputSchema: layoutChangesJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createEvaluateLayoutChangesHandler(store),
    },
    {
      name: "apply_layout_changes",
      title: "Apply an atomic layout change batch",
      description:
        "Apply an ordered changes array of 1–25 project commands atomically and undoable as one step. Any command failure or final layout error/unreachable entity rejects the entire batch without changing state or history. Intermediate layouts are never committed. A successful apply can still leave warnings: inspect validation and accessImpact. Returns per-change outcomes and generated IDs. Commands may reference existing canonical IDs, not guessed IDs for entities created earlier in this batch. Uses the same input as evaluate_layout_changes, with final validation against the live project.",
      inputSchema: layoutChangesJsonSchema,
      execute: createApplyLayoutChangesHandler(store),
    },
  ];
}

export function registerRoomTools(
  documentValue: Document,
  controller: AbortController,
  store: ProjectStore,
): Promise<ToolSetRegistrationResult> {
  return registerToolSet(documentValue, controller, createRoomWebMcpTools(store));
}
