import type { ProjectStore } from "@/features/creator/store/project-store";

import {
  createAddObstacleHandler,
  createConfigureRoomHandler,
  createGetProjectStateHandler,
  createRemoveObstacleHandler,
  createUpdateObstacleHandler,
  createUpdateProjectSettingsHandler,
  createValidateLayoutHandler,
} from "./room-tool-handlers";
import {
  addObstacleJsonSchema,
  configureRoomJsonSchema,
  getProjectStateJsonSchema,
  removeObstacleJsonSchema,
  updateObstacleJsonSchema,
  updateProjectSettingsJsonSchema,
  validateLayoutJsonSchema,
} from "./room-tool-schemas";
import { registerToolSet, type ToolSetRegistrationResult } from "./register-tool-set";
import type { WebMcpTool } from "./types";

const SPATIAL_INPUT_NOTE =
  "Positions are the minimum corner of the rotated footprint. Dimensions and positions use integer centimeters; rotation is 0, 90, 180, or 270 degrees. Spatially invalid layouts may still be applied and returned with validation issues.";

export function createRoomWebMcpTools(store: ProjectStore): readonly WebMcpTool[] {
  return [
    {
      name: "get_project_state",
      title: "Get current room project state",
      description:
        "Read the live room project, settings, obstacles, deterministic validation, revision, and manual undo/redo availability. Canonical obstacle IDs from this result can be used by update and remove tools.",
      inputSchema: getProjectStateJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createGetProjectStateHandler(store),
    },
    {
      name: "configure_room",
      title: "Configure room dimensions",
      description: `Set the room width, depth, and height in positive integer centimeters. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: configureRoomJsonSchema,
      execute: createConfigureRoomHandler(store),
    },
    {
      name: "update_project_settings",
      title: "Update room project settings",
      description:
        "Update a non-empty patch containing the non-negative integer PLN budget and/or up to five canonical training goals. This creates one shared manual undo step when values change.",
      inputSchema: updateProjectSettingsJsonSchema,
      execute: createUpdateProjectSettingsHandler(store),
    },
    {
      name: "add_obstacle",
      title: "Add a room obstacle or unavailable zone",
      description: `Add a physical obstacle or unavailable zone. The canonical obstacle ID is generated by the project and returned; callers must not supply an ID. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: addObstacleJsonSchema,
      execute: createAddObstacleHandler(store),
    },
    {
      name: "update_obstacle",
      title: "Update a room obstacle or unavailable zone",
      description: `Update one canonical obstacle ID using a non-empty patch. A locked obstacle accepts only the exact patch { locked: false } until unlocked. ${SPATIAL_INPUT_NOTE}`,
      inputSchema: updateObstacleJsonSchema,
      execute: createUpdateObstacleHandler(store),
    },
    {
      name: "remove_obstacle",
      title: "Remove a room obstacle or unavailable zone",
      description:
        "Remove the obstacle or unavailable zone with a canonical ID returned by get_project_state or add_obstacle. Locked obstacles must be unlocked first.",
      inputSchema: removeObstacleJsonSchema,
      execute: createRemoveObstacleHandler(store),
    },
    {
      name: "validate_layout",
      title: "Validate the current room layout",
      description:
        "Read the live deterministic layout validation and its revision without changing state or history. Reports out-of-room, height, collision, and unavailable-zone issues for canonical obstacle IDs.",
      inputSchema: validateLayoutJsonSchema,
      annotations: { readOnlyHint: true },
      execute: createValidateLayoutHandler(store),
    },
  ];
}

export function registerRoomTools(
  documentValue: Document,
  controller: AbortController,
  store: ProjectStore,
): Promise<ToolSetRegistrationResult> {
  return registerToolSet(documentValue, controller, createRoomWebMcpTools(store));
}
